on: [push]

jobs:
name: Regula
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Regula
uses: fugue/regula-action@v2.6.1
env:
FUGUE_API_ID: ${{ secrets.FUGUE_API_ID }}
FUGUE_API_SECRET: ${{ secrets.FUGUE_API_SECRET }}
with:
upload: "true"
sync: "true"
